#logging.level.org.springframework.kafka.listener: DEBUG

spring:
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        # for ordering
        max.in.flight.requests.per.connection: 1
        enable.idempotence: true
        # retries: 10000
        delivery.timeout.ms: 300000 # 5 minutes
        retry.backoff.ms: 1000
        acks: all

    bootstrap-servers: localhost:9092

tpd:
  topic-name: advice-topic
