version: '3.7'

services:
  kafka:
    image: confluentinc/cp-kafka:7.0.0
    container_name: kafka
    restart: unless-stopped
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://kafka:29092,PLAINTEXT_HOST://127.0.0.1:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'INTERNAL://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: 'false'
    volumes:
      - ./docker/kafka/entrypoint.sh:/sbin/entrypoint.sh:z
      - kafka_data:/var/lib/kafka/data:z
      - confluent_config_data:/etc/confluent/docker:z
    # https://github.com/confluentinc/cp-all-in-one/blob/7.0.0-post/cp-all-in-one-kraft/docker-compose.yml
    entrypoint: /sbin/entrypoint.sh

  # https://docs.confluent.io/current/ksql/docs/installation/install-ksql-with-docker.html
  ksqldb:
    image: confluentinc/ksqldb-server:0.22.0
    container_name: ksqldb
    restart: unless-stopped
    ports:
      - "8088:8088"
    depends_on:
      - kafka
    environment:
      # https://docs.ksqldb.io/en/latest/operate-and-deploy/installation/install-ksqldb-with-docker/#mount-volumes
      KSQL_BOOTSTRAP_SERVERS: "kafka:29092"
      KSQL_LISTENERS: "http://0.0.0.0:8088"
      KSQL_CONFLUENT_SUPPORT_METRICS_ENABLE: 'false'


# docker exec -it ksqldb-cli ksql http://ksqldb:8088
#  ksqldb-cli:
#    image: confluentinc/ksqldb-cli:0.22.0
#    container_name: ksqldb-cli
#    depends_on:
#      - kafka
#      - ksqldb
#    entrypoint: /bin/sh
#    tty: true

volumes:
  kafka_data:
  confluent_config_data: