CREATE TABLE users(
    userid BIGINT PRIMARY KEY,
    registertime BIGINT,
    gender VARCHAR,
    regionid VARCHAR
) WITH (
    KAFKA_TOPIC = 'users',
    VALUE_FORMAT='JSON',
    PARTITIONS=4,
    REPLICAS=1
);

CREATE TABLE USERS_QUERYABLE AS SELECT * FROM USERS;

CREATE TABLE USERS_DELETED (userid BIGINT PRIMARY KEY, DUMMY VARCHAR)
    WITH (KAFKA_TOPIC='users', VALUE_FORMAT='KAFKA');